remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Gustavo Adolfo Vanegas Marin
submodulo: Lógica de Programación
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/foto-7af27.appspot.com/o/foto%20hdv.png?alt=media&token=66263281-2e6a-43ca-b0a2-f850b2a88905

